name: Deploy Bitget Trader

on:
  push:
    branches: [ main ]
    paths: [ 'bitget_trader/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          cd bitget_trader
          pip install -r requirements.txt
          nohup streamlit run app.py --server.port ${{ secrets.PORT }} &